#bridge-file-version: #5
summon armor_stand ~4 ~ ~
tag @e[r=3, type=armor_stand] add isexc_fire_circle_spell
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace air 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace tallgrass 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace snow_layer 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace red_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ fill ~ ~ ~ ~ ~ ~ fire 0 replace yellow_flower 0
execute @e[tag=isexc_fire_circle_spell] ~ ~ ~ tp ^ ^ ^0.5 ~10 ~
effect @e[tag=isexc_fire_circle_spell] intant_damage 5 1 true
title @s actionbar  §7Spell Successfully Cast: §3FIRE CIRCLE